# Generated by Django 5.0.6 on 2024-07-04 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.CharField(max_length=100)),
                (
                    "tracking_number",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
